### ISSUE TITLE
Cascading merge fails inconsistently

### ISSUE THREAD

**Issue by snps-swamyt** [devimur2021/Sentiment-Based-Product-Recommendation-System#4]
**Problem statement:**
We are using GitHub action ActionsDesk/cascading-downstream-merge, this allows us to cascade pull request merges to newer releases.
This was working well for over 6 months now.

We started facing issues in June/2024, where the action was able to create the pull requests to cascade the changes, there was a problem with merging the pull requests created by ActionsDesk/cascading-downstream-merge GitHub action.

**Issue Analysis:**
405 - Method not allowed - message: 'Base branch was modified. Review and try the merge again.',

The above is the error reported in pipelines, I found a thread that explains this issue, I have added a snippet from accepted answer below.
https://github.com/orgs/community/discussions/24462

Answer snippet:
If you’ve noticed that sometimes it takes a second or two for the “this branch can be merged” icon to go green in the GItHub UI, that’s because there’s a process that needs to verify that the branch is mergeable. When you get that message it means that you need to try again because that process hasn’t yet finished.

_Looks like the pull requests created by GitHub action are not ready to be merged as soon as it is created, and hence the error._

**Request to GitHub team:**
The issue is resolved on it's own after 15 days or so, without us or the GitHub admin changing anything, neither had we changed anything before the issue appeared.

Need help in understanding the issue and if possible a fix for it.

**Comment by igorcosta** [comment]
We had a few internal cascade events internally into our dispatch/event systems that halted some operations while we were migrating a few system endpoints. Maybe there's a correlation to that, when you say 15 days or so, can you be specific? I just want to double check and see if your account got directly affected by our system updates.

**Comment by devimur2021** [comment]
@igorcosta i see first issue reported on May 29th.

**Comment by snps-swamyt** [comment]
Hello @igorcosta ,

I am sharing timestamp from one of my validation runs: Sat, 08 Jun 2024 17:18:14 GMT

Action used: ActionsDesk/cascading-downstream-merge@v1.1.0

**Comment by devimur2021** [comment]
@igorcosta today cascading merge again failed to run successfully. Action is getting Http 500 , below is the snippet of the error message 

RequestError [HttpError]
   at /runner/_work/_actions/ActionsDesk/cascading-downstream-merge/v1.1.0/dist/index.js:4085:21
   at processTicksAndRejections (node:internal/process/task_queues:96:5)
   at async cascadingBranchMerge (/runner/_work/_actions/ActionsDesk/cascading-downstream-merge/v1.1.0/dist/index.js:8845:9) {
status: 500,
response: {
   url: 'https://snpsghes-eda.internal.synopsys.com/api/v3/repos/eda/siliconda-cloud/pulls/6257/merge',
   status: 500,
   headers: {
     connection: 'close',
     date: 'Thu, 11 Jul 2024 12:52:08 GMT',
     server: 'GitHub.com',
     'transfer-encoding': 'chunked',
     'x-frame-options': 'DENY'
   },
   data: ''
 },

**Comment by igorcosta** [comment]
I had a look on the logs and I can't determine if your account was affected, I see a few errors similar to this one processTicksAndRejections (node:internal/process/task_queues:96:5) that was related to the casading-down-stream-merge as it was relying on an older version of nodejs, which we deprecated. 

Please try again and let me know if you still have this issue.
